### ISSUE TITLE
Console Error while excetuting command

### ISSUE THREAD

**Issue by RexCodes** [TJPlaysNow/Discord-Bot-API---JDA#3]
When I try to run a command, there is an error thrown in the console:

[14:08:43 INFO]: [ProgramBot] [INFO]: Running command mute
[14:08:43 WARN]: [JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
[14:08:43 WARN]: java.lang.NoClassDefFoundError: net/dv8tion/jda/core/Permission
[14:08:43 WARN]:        at me.craftblock.discord.discordBotCommands.Command_Mute.getPermissionNeeded(Command_Mute.java:22)
[14:08:43 WARN]:        at com.tjplaysnow.discord.object.Bot.lambda$new$5(Bot.java:75)
[14:08:43 WARN]:        at com.tjplaysnow.discord.object.Bot.onEvent(Bot.java:365)
[14:08:43 WARN]:        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
[14:08:43 WARN]:        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
[14:08:43 WARN]:        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
[14:08:43 WARN]:        at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
[14:08:43 WARN]:        at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
[14:08:43 WARN]:        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
[14:08:43 WARN]:        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
[14:08:43 WARN]:        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
[14:08:43 WARN]:        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
[14:08:43 WARN]:        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
[14:08:43 WARN]:        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
[14:08:43 WARN]:        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[14:08:43 WARN]:        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[14:08:43 WARN]:        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[14:08:43 INFO]: [ProgramBot] [INFO]: Running command mute

**Comment by Moose1301** [comment]
Does your bot have admin permission
